### ISSUE TITLE
About section improper responsiveness

### ISSUE THREAD

**Issue by berwinxie** [acm-uiuc/rp2016#103]
![screen shot 2016-09-01 at 14 23 08](https://cloud.githubusercontent.com/assets/5169056/18181201/aee7f508-704f-11e6-9096-690112bcc065.png)

**Comment by bluedrops** [comment]
I'm pretty sure I fixed this last night and merged it with PR #96 
did you pull the latest? I don't see this error on my end at any breakpoint

**Comment by sskhandek** [comment]
I can't reproduce this either

**Comment by berwinxie** [comment]
I was running on the actual site?

**Comment by berwinxie** [comment]
Oh, I guess it doesn't happen on my local master, but still happens on reflectionsprojections.com

**Comment by bluedrops** [comment]
The actual site doesn't reflect all the changes we've made recently; you'll clone the repo and checkout 'master' to get the real current state of the site
